version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: carmigo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
   image: flyway/flyway
   command: -url=jdbc:postgresql://db/carmigo -schemas=public -user=admin
     -password=password -connectRetries=5 migrate
   volumes:
     - ./migrations:/flyway/sql
   depends_on:
     - db
volumes:
  db:
